apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: dv
    app.kubernetes.io/managed-by: ibm-dv-operator
    app.kubernetes.io/name: dv
  name: ibm-dv-provisioner-rolebinding
subjects:
- kind: ServiceAccount
  name: zen-editor-sa
roleRef:
  kind: Role
  name: ibm-dv-provisioner-role
  apiGroup: rbac.authorization.k8s.io
