apiVersion: v1
kind: ConfigMap
metadata:
  name: dv-provision-cm
  labels:
    app: dvprovision
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
  create_dv_instance.sh: |-
    #!/bin/sh

    ################################################################################
    #
    # Licensed Materials - Property of IBM
    #
    # "Restricted Materials of IBM"
    #
    # (C) COPYRIGHT IBM Corp. 2018 All Rights Reserved.
    #
    # US Government Users Restricted Rights - Use, duplication or
    # disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
    #
    ################################################################################

    echo "done"
  ibm_dv_provisioner_role.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      labels:
        app.kubernetes.io/component: addon
        app.kubernetes.io/instance: dv
        app.kubernetes.io/managed-by: ibm-dv-operator
        app.kubernetes.io/name: dv
      name: ibm-dv-provisioner-role
    rules:
    - apiGroups:
      - db2u.databases.ibm.com
      resources:
      - bigsqls
      - db2uclusters
      - dvs
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  ibm_dv_provisioner_rolebinding.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      labels:
        app.kubernetes.io/component: operator
        app.kubernetes.io/instance: dv
        app.kubernetes.io/managed-by: ibm-dv-operator
        app.kubernetes.io/name: dv
      name: ibm-dv-provisioner-rolebinding
    subjects:
    - kind: ServiceAccount
      name: zen-editor-sa
    roleRef:
      kind: Role
      name: ibm-dv-provisioner-role
      apiGroup: rbac.authorization.k8s.io
  newdv.json: |-
    {
        "addon_type": "dv",
        "display_name": "data-virtualization",
        "namespace": "gitops-cp4d-instance",
        "addon_version": "1.7.5",
        "create_arguments": {
          "parameters": {
            "enableHostIPC": "false",
            "resources.dv.requests.memory": "16Gi",
            "image.pullPolicy": "IfNotPresent",
            "persistence.cachingpv.storageClass": "portworx-db2-rwx-sc",
            "persistence.cachingpv.size": "50Gi",
            "persistence.size": "50Gi",
            "persistence.workerpv.storageClass": "portworx-db2-rwx-sc",
            "persistence.workerpv.size": "50Gi",
            "persistence.storageClass": "portworx-db2-rwx-sc",
            "resources.dv.requests.cpu": "4",
            "workerCount": "1"
          },
          "resources": {
            "cpu": "4",
            "memory": "16"
          },
          "description": "Data Virtualization",
          "metadata": {}
        },
        "transient_fields": {}
      }
