apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: addon
    app.kubernetes.io/instance: dv
    app.kubernetes.io/managed-by: ibm-dv-operator
    app.kubernetes.io/name: dv
  name: ibm-dv-provisioner-role
rules:
- apiGroups:
  - db2u.databases.ibm.com
  resources:
  - bigsqls
  - db2uclusters
  - dvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
